import torch, random, numpy as np
import os, json, pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import math
from PIL import Image
from torchvision import transforms
from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision import models
from torchsummary import summary
import torch.nn.functional as F
from PIL import Image

# -----------------------------------------------------------------------------------
# Reproducibility setup (same pattern used across projects)

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"[info] Using device: {device}")
print(f"[info] Random seed fixed at {SEED}")
# -----------------------------------------------------------------------------------
# Verify and Summarize the Dataset
# Dataset paths (generated by the prep cell earlier)
DATA_ROOT = Path("./data/caltech101_10")
MANIFEST = DATA_ROOT / "manifest.csv"
CLASS_NAMES_JSON = DATA_ROOT / "class_names.json"

# Basic checks
assert DATA_ROOT.exists(), f"Dataset folder not found at {DATA_ROOT}"
assert MANIFEST.exists() and CLASS_NAMES_JSON.exists(), "Manifest or class_names.json missing"

# Load metadata
df = pd.read_csv(MANIFEST)
with open(CLASS_NAMES_JSON, "r", encoding="utf-8") as f:
    class_names = json.load(f)

print(f"[info] Found {len(df)} total images")
print(f"[info] Class names ({len(class_names)}): {class_names}")

# Summary by split
print("\n[summary] Images per split:")
print(df["split"].value_counts())

# Per-class per-split counts
counts = df.groupby(["split", "class_name"]).size().unstack(fill_value=0)
print("\n[summary] Per-class counts by split:")
display(counts)

# Check for any missing files
missing = [p for p in df["filepath"] if not Path(p).exists()]
print(f"\n[check] Missing files: {len(missing)} (should be 0)")
# -----------------------------------------------------------------------------------
# Visualise sample images
# Basic image loader
tfm_preview = transforms.Compose([
    transforms.Resize(128),
    transforms.CenterCrop(128),
])

# Sample a few random training images
sample_df = df[df["split"]=="train"].sample(12, random_state=42).reset_index(drop=True)

cols, rows = 6, 2
plt.figure(figsize=(cols*2.2, rows*2.2))

for i, row in sample_df.iterrows():
    img = Image.open(row["filepath"]).convert("RGB")
    img = tfm_preview(img)
    plt.subplot(rows, cols, i+1)
    plt.imshow(img)
    plt.title(row["class_name"], fontsize=9)
    plt.axis("off")

plt.suptitle("Sample images from Caltech-101 (10-class subset)", fontsize=12)
plt.tight_layout()
plt.show()
# -----------------------------------------------------------------------------------
# Define Transforms and Constants
# ImageNet normalization constants
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# Define the preprocessing pipeline
transform = transforms.Compose([
    transforms.Resize(128),
    transforms.CenterCrop(128),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
])
# -------------------------------------------
# Build Dataset Objects and DataLoaders
# -------------------------------------------
print("[info] Transformation pipeline ready.")
# Load dataset from prepared folders
train_dir = DATA_ROOT / "train"
val_dir   = DATA_ROOT / "val"
test_dir  = DATA_ROOT / "test"

train_ds = datasets.ImageFolder(train_dir, transform=transform)
val_ds   = datasets.ImageFolder(val_dir, transform=transform)
test_ds  = datasets.ImageFolder(test_dir, transform=transform)

# DataLoaders (small batch size for CPU runs)
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True, num_workers=0)
val_loader   = DataLoader(val_ds, batch_size=32, shuffle=False, num_workers=0)
test_loader  = DataLoader(test_ds, batch_size=32, shuffle=False, num_workers=0)

print(f"[info] Dataset sizes → train={len(train_ds)}, val={len(val_ds)}, test={len(test_ds)}")
print(f"[info] Classes: {train_ds.classes}")
# -------------------------------------------
# Visualize a Mini-Batch
# -------------------------------------------
# Helper function to unnormalize images for display
def unnormalize(img_tensor):
    img = img_tensor.clone()
    for c, (m, s) in enumerate(zip(IMAGENET_MEAN, IMAGENET_STD)):
        img[c] = img[c] * s + m
    return img.clamp(0, 1)

# Fetch one mini-batch
images, labels = next(iter(train_loader))

# Unnormalize for display
images_disp = [unnormalize(img) for img in images[:8]]

# Create grid
grid = torchvision.utils.make_grid(images_disp, nrow=8)
plt.figure(figsize=(14, 2.5))
plt.imshow(grid.permute(1, 2, 0))
plt.title("Mini-batch samples after preprocessing")
plt.axis("off")
plt.show()

print(f"Labels for these samples: {[train_ds.classes[i] for i in labels[:8].tolist()]}")
# -----------------------------------------------------------------------------------
# Load the Pretrained Model
# Load pretrained ResNet18 model
model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

print("[info] Pretrained ResNet-18 loaded successfully.")
# ----------------------------------------
# Inspect the Architecture
# ----------------------------------------
# Move to CPU (since we are in concept notebook)
device = torch.device("cpu")
model.to(device)

# Display model structure and parameter count
summary(model, input_size=(3, 128, 128))

layer_hierarchy = [name for name, _ in model.named_children()]
print("Top-level children:", layer_hierarchy)
# ----------------------------------------
# Visualize the Layer Hierarchy
# ----------------------------------------
# Show hierarchical layer structure
print(model)

# Quick count of total and trainable parameters
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\n[summary] Total parameters: {total_params:,}")
print(f"[summary] Trainable parameters: {trainable_params:,}")
# -----------------------------------------------------------------------------------
# Freeze the Pretrained Backbone
# Safety: ensure we have a model (from Section 4); otherwise load it
try:
    _ = model
except NameError:
    model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)

# Move to device (kept CPU-friendly in this NB)
device = torch.device("cpu")
model = model.to(device)

# 1) Freeze all pretrained params
for p in model.parameters():
    p.requires_grad = False

print("[info] Frozen all backbone parameters.")
# ------------------------------------------
# Replace and Initialize the Classifier Head
# ------------------------------------------
# Determine number of classes from our prepared metadata if available; fallback to 10
try:
    num_classes = len(class_names)
except NameError:
    num_classes = 10

# 2) Replace the final FC layer with a new head
in_features = model.fc.in_features
model.fc = nn.Linear(in_features, num_classes)

# 3) Kaiming initialization (good default for ReLU nets)
nn.init.kaiming_uniform_(model.fc.weight, a=math.sqrt(5))
if model.fc.bias is not None:
    fan_in, _ = nn.init._calculate_fan_in_and_fan_out(model.fc.weight)
    bound = 1 / math.sqrt(fan_in)
    nn.init.uniform_(model.fc.bias, -bound, bound)

model = model.to(device)
model.eval()

print(f"[info] Replaced classifier head: in_features={in_features}, out_features={num_classes}")
# ------------------------------------------
# Verify Trainable Parameters Only in the New Head
# ------------------------------------------
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
trainable_names = [n for n, p in model.named_parameters() if p.requires_grad]

print(f"[summary] Total parameters: {total_params:,}")
print(f"[summary] Trainable parameters (should be only the new head): {trainable_params:,}")
print("[summary] Trainable parameter tensors:")
for n in trainable_names:
    print("  •", n)

# Simple assert (will raise if something other than the new head is trainable)
assert all(n.startswith("fc.") for n in trainable_names), "Unexpected trainable parameters outside the classifier head."
print("[check] Only the classifier head is trainable. Good to proceed.")
# -----------------------------------------------------------------------------------
# Run a Zero-Shot Forward Pass
# Fetch one mini-batch from the validation loader
images, labels = next(iter(val_loader))
images, labels = images.to(device), labels.to(device)

# Run through the frozen model (no grad tracking)
with torch.no_grad():
    logits = model(images)
    probs = F.softmax(logits, dim=1)

print(f"[check] Logits shape: {logits.shape}")
print(f"[check] Probabilities shape: {probs.shape}")
# ------------------------------------------
#Inspect Predictions for a Few Samples
# ------------------------------------------
# Pick 5 random samples from the batch
idxs = np.random.choice(len(images), size=5, replace=False)

plt.figure(figsize=(12, 4))
for i, idx in enumerate(idxs):
    img = images[idx].cpu()
    label = labels[idx].item()
    pred_class = torch.argmax(probs[idx]).item()
    confidence = probs[idx][pred_class].item()

    # Unnormalize image for display
    img_disp = img.clone()
    for c, (m, s) in enumerate(zip(IMAGENET_MEAN, IMAGENET_STD)):
        img_disp[c] = img_disp[c] * s + m

    plt.subplot(1, 5, i + 1)
    plt.imshow(img_disp.permute(1, 2, 0).clamp(0, 1))
    plt.axis("off")
    plt.title(
        f"True: {train_ds.classes[label]}\nPred: {train_ds.classes[pred_class]}\nConf: {confidence:.2f}",
        fontsize=9,
    )

plt.suptitle("Zero-shot predictions before training (random head)", fontsize=13)
plt.tight_layout()
plt.show()
# -----------------------------------------------------------------------------------
# Visualize the First Convolutional Layer Filters
filters = model.conv1.weight.detach().cpu()
num_filters = 32
cols = 8
rows = num_filters // cols

plt.figure(figsize=(cols * 1.6, rows * 1.6))
for i in range(num_filters):
    f = filters[i]
    f = (f - f.min()) / (f.max() - f.min())  # normalize for display
    plt.subplot(rows, cols, i + 1)    
    plt.imshow(f.permute(1,2,0))
    plt.axis("off")
plt.suptitle("Visualization of first-layer filters (Conv1)", fontsize=13)
plt.tight_layout()
plt.show()
# ------------------------------------------
# Visualizing pretrained filter responses on a real image
# ------------------------------------------
import requests
img = Image.open("dog.jpg")

plt.figure(figsize=(4,4))
plt.imshow(img)
plt.title("Original Image (Input to Conv1)")
plt.axis("off")
plt.show()

# --- Step 2: Preprocess and run through Conv1 ---
weights = models.ResNet18_Weights.IMAGENET1K_V1   # keep this reference for transforms
preprocess = weights.transforms()           # correct: use the transforms defined by weights
x = preprocess(img).unsqueeze(0)

with torch.no_grad():
    feat = model.conv1(x)[0]  # [C,H,W] feature maps


# --- Step 3: Visualize a few feature responses ---
plt.figure(figsize=(cols * 1.6, rows * 1.6))
for i in range(num_filters):
    plt.subplot(rows, cols, i + 1)    
    plt.imshow(feat[i].cpu(), cmap="gray")
    plt.axis("off")

plt.suptitle("First Conv Layer Feature Responses", fontsize=12)
plt.tight_layout()
plt.show()
# -----------------------------------------------------------------------------------

# Apply same preprocessing as before
prep_tfm = transforms.Compose([
    transforms.Resize(128),
    transforms.CenterCrop(128),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

input_tensor = prep_tfm(img).unsqueeze(0).to(device)

# Define a hook to capture outputs of specific layers
feature_maps = {}

def get_activation(name):
    def hook(model, input, output):
        feature_maps[name] = output.detach().cpu()
    return hook

# Register hooks on two intermediate layers
model.layer1[0].conv1.register_forward_hook(get_activation("layer1"))
model.layer2[0].conv1.register_forward_hook(get_activation("layer2"))
model.layer3[0].conv1.register_forward_hook(get_activation("layer3"))

# Forward pass
with torch.no_grad():
    _ = model(input_tensor)

# Plot original image + selected feature maps
fig, axes = plt.subplots(1, 3, figsize=(10, 4))
axes[0].imshow(img)
axes[0].set_title("Original image")
axes[0].axis("off")

display_order = ["layer1", "layer2", "layer3"]
for i, layer_name in enumerate(display_order, start=0):
    fmap = feature_maps[layer_name]
    fmap_mean = fmap[0].mean(dim=0)
    axes[i].imshow(fmap_mean, cmap="viridis")
    axes[i].set_title(f"{layer_name} mean activation")
    axes[i].axis("off")


plt.suptitle("Feature maps from early and deeper layers", fontsize=13)
plt.tight_layout()
plt.show()

# -----------------------------------------------------------------------------------
# Task 11.1.8.1: Plot filters from the “second conv”
CT_r18 = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1).to('cpu')
CT_conv2_filters = CT_r18.layer1[0].conv2.weight.detach().cpu()  # [C_out, C_in, k, k]

num = min(32, CT_conv2_filters.shape[0])
cols, rows = 8, (num + 7) // 8
plt.figure(figsize=(cols*1.6, rows*1.6))
for i in range(num):
    f = CT_conv2_filters[i]
    # collapse in_channels by taking mean for visualization
    f2 = f.mean(dim=0)
    f2 = (f2 - f2.min()) / (f2.max() - f2.min() + 1e-6)

# -----------------------------------------
# Task 11.1.8.2: First-conv feature responses on a different image
# -----------------------------------------
# Assume val_loader, IMAGENET_MEAN/STD exist (from earlier sections)
CT_img2_idx = 5  # choose any valid index in the first batch
CT_r18b = models.resnet18(weights==models.ResNet18_Weights.IMAGENET1K_V1).to('cpu')
CT_r18b.eval()

# Grab a batch and get a different validation image
CT_images, CT_labels = next(iter(val_loader))
CT_x = CT_images[CT_img2_idx:CT_img2_idx+1]

# Compute feature maps
with torch.no_grad():
    CT_feat_maps1 = CT_r18b.conv1(CT_x)[0]   # [C,H,W]
# -----------------------------------------
# Task 11.1.8.3: Mean activations for layer1, layer3, layer4
# -----------------------------------------
CT_r18c = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1).to('cpu').eval()
CT_feature_maps = {}

def CT_get_hook(name):
    def hook(m, inp, out):
        CT_feature_maps[name] = out.detach().cpu()
    return hook

# Register hooks
CT_r18c.layer1.register_forward_hook(CT_get_hook("layer1"))
CT_r18c.layer3.register_forward_hook(CT_get_hook("layer3"))
CT_r18c.layer4.register_forward_hook(CT_get_hook("layer4"))

with torch.no_grad():
    _ = CT_r18c(CT_x)  # reuse CT_x from last code task

# Build dictionary of mean activations
CT_mean_act = {}
for k in ["layer1","layer3","layer4"]:
    fmap = CT_feature_maps[k][0]  # Remove batch dimension: [C, H, W]
    CT_mean_act[k] = fmap.mean(dim=0)  # Mean over channels: [H, W]

# Plot 3 panels: layer1, layer3, layer4
fig, axes = plt.subplots(1, 3, figsize=(12, 4))
for i, k in enumerate(["layer1", "layer3", "layer4"]):
    axes[i].imshow(CT_mean_act[k], cmap="viridis")
    axes[i].set_title(f"{k} mean activation")
    axes[i].axis("off")
plt.suptitle("Mean activations for layer1, layer3, layer4", fontsize=13)
plt.tight_layout()
plt.show()
# -----------------------------------------------------------------------------------